package com.model;
// Generated Oct 19, 2015 2:31:40 PM by Hibernate Tools 4.3.1

/**
 * HwConfig generated by hbm2java
 */
public class HwConfig implements java.io.Serializable {

	private Integer id;
	private String boardSku;
	private String boardFab;
	private String chassis;
	private String hsbp;
	private String pus;
	private String cpu;
	private String memory;

	public HwConfig() {
	}

	public HwConfig(String boardSku, String boardFab, String chassis, String hsbp, String pus, String cpu,
			String memory) {
		this.boardSku = boardSku;
		this.boardFab = boardFab;
		this.chassis = chassis;
		this.hsbp = hsbp;
		this.pus = pus;
		this.cpu = cpu;
		this.memory = memory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBoardSku() {
		return this.boardSku;
	}

	public void setBoardSku(String boardSku) {
		this.boardSku = boardSku;
	}

	public String getBoardFab() {
		return this.boardFab;
	}

	public void setBoardFab(String boardFab) {
		this.boardFab = boardFab;
	}

	public String getChassis() {
		return this.chassis;
	}

	public void setChassis(String chassis) {
		this.chassis = chassis;
	}

	public String getHsbp() {
		return this.hsbp;
	}

	public void setHsbp(String hsbp) {
		this.hsbp = hsbp;
	}

	public String getPus() {
		return this.pus;
	}

	public void setPus(String pus) {
		this.pus = pus;
	}

	public String getCpu() {
		return this.cpu;
	}

	public void setCpu(String cpu) {
		this.cpu = cpu;
	}

	public String getMemory() {
		return this.memory;
	}

	public void setMemory(String memory) {
		this.memory = memory;
	}

}
