package com.model;
// Generated Oct 26, 2015 10:12:44 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TestResult generated by hbm2java
 */
public class TestResult implements java.io.Serializable {

	private Integer testResultId;
	private String caseResult;
	private String trackerNo;
	private String notes;
	private Date recordTime;
	private String testType;
	private Product product; 
	private SwConfig swConfig;
	private HwConfig hwConfig;
	private TestCase tcase; 
	

	public TestResult() {
	}

	public TestResult(String caseResult,String tracker,String note, Date recordTime, String tType, Product product, SwConfig swConfig, HwConfig hwConfig, TestCase tcase) {
		this.caseResult = caseResult;
		this.recordTime = recordTime;
		this.notes=note;
		this.trackerNo=tracker;
		this.testType=tType;
		this.product = product;
		this.swConfig = swConfig;
		this.hwConfig = hwConfig;
		this.tcase = tcase;
	}

	public Integer getTestResultId() {
		return this.testResultId;
	}

	public void setTestResultId(Integer testResultId) {
		this.testResultId = testResultId;
	}

	public String getCaseResult() {
		return this.caseResult;
	}

	public void setCaseResult(String caseResult) {
		this.caseResult = caseResult;
	}

	public String getTrackerNo() {
		return this.trackerNo;
	}

	public void setTrackerNo(String trackerNo) {
		this.trackerNo = trackerNo;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public SwConfig getswConfig() {
		return this.swConfig;
	}

	public void setswConfig(SwConfig swconfig) {
		this.swConfig = swconfig;
	}

	public HwConfig gethwConfig() {
		return this.hwConfig;
	}

	public void sethwConfig(HwConfig hwconfig) {
		this.hwConfig = hwconfig;
	}

	public TestCase gettcase() {
		return this.tcase;
	}

	public void settcase(TestCase tcase) {
		this.tcase =tcase;
	}

}
