package com.model;
// Generated Oct 19, 2015 2:31:40 PM by Hibernate Tools 4.3.1

/**
 * TestCase generated by hbm2java
 */
public class TestCase implements java.io.Serializable {

	private Integer id;
	private String testCatagory;
	private String testTitle;
	private String testCaseVersion;
	private int productId;

	public TestCase() {
	}

	public TestCase(String testCatagory, String testTitle, String testCaseVersion, int productId) {
		this.testCatagory = testCatagory;
		this.testTitle = testTitle;
		this.testCaseVersion = testCaseVersion;
		this.productId = productId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTestCatagory() {
		return this.testCatagory;
	}

	public void setTestCatagory(String testCatagory) {
		this.testCatagory = testCatagory;
	}

	public String getTestTitle() {
		return this.testTitle;
	}

	public void setTestTitle(String testTitle) {
		this.testTitle = testTitle;
	}

	public String getTestCaseVersion() {
		return this.testCaseVersion;
	}

	public void setTestCaseVersion(String testCaseVersion) {
		this.testCaseVersion = testCaseVersion;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

}
