package com.model;
// Generated Oct 19, 2015 2:31:40 PM by Hibernate Tools 4.3.1

/**
 * TestCase generated by hbm2java
 */
import java.util.*;
public class TestCase implements java.io.Serializable {

	private Integer id;
	private String testCatagory;
	private String testTitle;
	private String testCaseVersion;
	private Set<Product> products=new HashSet<Product>();
	private Set<TestResult> results=new HashSet<TestResult>();

	public TestCase() {
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		//System.out.println("in equals"+o);
		 if(o == null)
	        {
			 System.out.println(" o == null");
	            return false;
	        }
	        if (o == this)
	        {
	        	System.out.println(" o == this");
	           return true;
	        }
	        if (getClass() != o.getClass())
	        {
	        	System.out.println("getClass() != o.getClass()");
	            return false;
	        }
	        TestCase e = (TestCase) o;
	        /*
	        System.out.println("this.getId() == e.getId())");
	        System.out.println(this.getId());
	        System.out.println(e.getId());
	        System.out.println(this.getId() == e.getId());
	        */
	        int i,j;
	        i= this.getId();
	        j=e.getId();
	        
	        return (i==j);
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
	    final int PRIME = 31;
	    int result = 1;
	    result = PRIME * result + getId();
	    return result;
	}

	public TestCase(String testCatagory, String testTitle, String testCaseVersion, int productId, Set<Product> products,Set<TestResult> results) {
		this.results=results;
		this.testCatagory = testCatagory;
		this.testTitle = testTitle;
		this.testCaseVersion = testCaseVersion;
		this.products=products; 
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTestCatagory() {
		return this.testCatagory;
	}

	public void setTestCatagory(String testCatagory) {
		this.testCatagory = testCatagory;
	}

	public String getTestTitle() {
		return this.testTitle;
	}

	public void setTestTitle(String testTitle) {
		this.testTitle = testTitle;
	}

	public String getTestCaseVersion() {
		return this.testCaseVersion;
	}

	public void setTestCaseVersion(String testCaseVersion) {
		this.testCaseVersion = testCaseVersion;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public Set<TestResult> getResults() {
		return this.results;
	}

	public void setResults(Set<TestResult> results) {
		this.results = results;
	}


}
